### ISSUE TITLE
Setup Discourse in testing environment

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/restarters.net#140]
https://meta.discourse.org/t/move-your-discourse-instance-to-a-different-server/15721

- [x] setup DNS record
- [x] setup droplet on Digital Ocean
- [ ] setup mailgun sandbox
- [ ] install Discourse
- [ ] import from backup
- [ ] run the remapping

**Comment by ngm** [comment]
Should be fairly straightforward - simply import one of the backups, and it should work apparently.

Questions

- it will be on a different URL, how does this effect things?

**Comment by ngm** [comment]
Extra notes here, including remapping URLs: https://meta.discourse.org/t/creating-a-duplicate-of-production-environment/61966/5

**Comment by ngm** [comment]
Is there a simple way to stop indexing of a Discourse test instance by search engines?

If nothing else, perhaps via robots.txt?

**Comment by ngm** [comment]
Need to avoid version mismatch, so will need to upgrade/reinstall Discourse on test.

**Comment by ngm** [comment]
Changing domain name: https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098

**Comment by ngm** [comment]
Live is currently Discourse 2.3.6

**Comment by ngm** [comment]
DigitalOcean Discourse from Marketplace is only 2.2.0.....

**Comment by ngm** [comment]
Probably best to do the install via this route: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by ngm** [comment]
That's installed 2.4.0-beta7.  Will need to see if this results in a version mismatch and if so, will have to see how to install the older version.

**Comment by ngm** [comment]
Not working 100%.

Getting JS errors, particularly with the 'Light' theme, but also other 'Original (light)' etc.

```
TypeError: Discourse.NavItem is undefined 4fd529dc58ad4d2e45670c2795e8b83b1eb63e67.js:10:1
    <anonymous> https://test-talk.rstrt.org/theme-javascripts/4fd529dc58ad4d2e45670c2795e8b83b1eb63e67.js?__ws=test-talk.rstrt.org:10

jQuery.Deferred exception: this.funcs[r] is not a function h</t.compile@https://test-talk.rstrt.org/assets/ember_jquery-c2cca4a19fd4c70eabc95b010a6d7643955ec2a2251aeb1d70f625773eebea21.js:1:363086

XML Parsing Error: syntax error
Location: https://test-talk.rstrt.org/logs/report_js_error
Line Number 1, Column 1: report_js_error:1:1
jQuery.Deferred exception: this._parentNode is null _createIFrame@https://meet.jit.si/external_api.js:1:23340
$@https://meet.jit.si/external_api.js:1:22660
@https://test-talk.rstrt.org/theme-javascripts/caa456e965f308b4a33a6f86a634ce54b2cf83a3.js?__ws=test-talk.rstrt.org:21:17
```

**Comment by ngm** [comment]
Will try to reinstall, matching version from prod, to rule out version mismatch being the issue.

**Comment by ngm** [comment]
According to this, you can install an older backup in to a newer version, and it should work fine: https://meta.discourse.org/t/how-do-you-install-an-earlier-version-of-discourse/31930/7

However I wonder if there's something in our theme or a theme component that might be causing an issue.

**Comment by ngm** [comment]
If I change `version` in `app.yml` to `stable`, then it should install 2.3.6.

**Comment by ngm** [comment]
That worked fine.

I had to change it in `templates/web.template.yml` before running `./discourse-setup`.
